### ISSUE TITLE
MultiOmics support

### ISSUE THREAD

**Issue by iblacksand** [bzhanglab/webgestalt_rust#5]
Add multiomics to the Rust library and the R package. Currently being developed, but the report is going to be the most difficult aspect to change.

## Tasks

- [x] Determine how users will input multiple lists
- [x] Implement three multi-omics methods
- [x] Develop new HTML reports
